### ISSUE TITLE
Trying to use 'proxyheader' results in a segfault

### ISSUE THREAD

**Issue by cyrillpetroff** [creaktive/LWP-Protocol-Net-Curl#19] opened 2023-06-10 14:30 UTC
Trying to send header to proxy only, getting segfault

```
#!/usr/bin/perl -w

$| = 1;

use LWP::Protocol::Net::Curl ssl_verifyhost => 0, ssl_verifypeer => 0, verbose => 1, proxy_ssl_verifypeer => 0, proxy_ssl_verifyhost => 0, headeropt => 1, proxyheader => ['ab: ba'];

use LWP::UserAgent;

my $ua = LWP::UserAgent->new();
$ua->proxy([ 'https' ] => 'http://45.144.165.248:8080');
$ua->agent('curl');

my $content = $ua->get('https://google.com/');

print $content->decoded_content;
```

```
root@cyrillpetroff:~# perl t.pl
*   Trying 45.144.165.248:8080...
* Connected to 45.144.165.248 (45.144.165.248) port 8080 (#0)
* allocate connect buffer
* Establish HTTP proxy tunnel to google.com:443
Segmentation fault (core dumped)
```

**Comment by creaktive** [comment] 2023-06-13 07:28
Thanks for investigating this, @cyrillpetroff!
The issue is with the underlying library, `Net::Curl`. Pushed the fix there: https://github.com/sparky/perl-Net-Curl/issues/73
Can you please check if it works?

**Comment by creaktive** [comment] 2023-06-16 09:32
Fixed upstream and released to CPAN: https://metacpan.org/release/SYP/Net-Curl-0.54

**Closed as completed by creaktive** 2023-06-16 09:32 UTC
